Marks = []
m1 = input("Enter marks of student: ")
Marks.append(m1)
m2 = input("Enter marks of student: ")
Marks.append(m2)
m3 = input("Enter marks of student: ")
Marks.append(m3)
m4 = input("Enter marks of student: ")
Marks.append(m4)
m5 = input("Enter marks of student: ")
Marks.append(m5)
print(Marks)
Marks.sort()
print(Marks)
